NethServer/ns8-webserver

build-images.sh

container alpine are faster, php-fpm from bitnami doesn't support alpine
review of https://github.com/NethServer/ns8-webserver/pull/1

Use alpine containers

---

imageroot/actions/create-vhost/10base
imageroot/templates/php-fpm-pool.conf

Set the uid 1 and a specific (unique) gid on the web root folder
The webroot folder is created at the first sftp upload by sftpgo of by the sftp  CLI
review of https://github.com/NethServer/ns8-webserver/pull/1

Set permission by uid and gid on the webroot folder

---

imageroot/actions/get-configuration/20read
imageroot/actions/get-configuration/validate-output.json
ui/src/views/Status.vue
ui/src/views/VirtualHosts.vue

When you install the webserver on the remote node the UI sends back in the web link  the hostname of the leader node which runs the UI and not the hostname of the remote node

Fix the node hostname in case of remote node

---

imageroot/actions/configure-module/60sftpgo_create_secret

With slow system we have an issue when the sftpgo container is not fully started and we try to initiate the first configuration. It seems that without the first configuration we cannot check the healtchek of the container  https://sftpgo.stoplight.io/docs/sftpgo/ae095616e4a79-health-check and the sftpgo container is able to answer to the systemd post action ping whereas it is not fully started or responsive.
Not the best fix but we need to wait
https://community.nethserver.org/t/ns8-configure-nginx-fails/21678/
```
Jun 07 20:55:07 R3-pve.rocky9-pve3.org webserver1[9762]: Traceback (most recent call last):
Jun 07 20:55:07 R3-pve.rocky9-pve3.org webserver1[9762]:   File "/home/webserver1/.config/actions/configure-module/60sftpgo_create_secret", line 44, in <module>
Jun 07 20:55:07 …
```

Wait the first time after slow system

---

README.md
imageroot/actions/create-vhost/30SystemdServices
imageroot/actions/update-vhost/30SystemdServices
imageroot/bin/download-php-fpm
imageroot/systemd/user/phpfpm@.service
imageroot/update-module.d/20restart

We use fixed version of php, before to start the container we pull the image and we tag it with a major version to use it locally
When we upgrade the module, before to restart the phpfpm@{7.4,8.0,8.1,8.2}.service we pull the image

download and tag x.y.z php version

---

imageroot/actions/clone-module/06copyenv
imageroot/actions/clone-module/60pull-php-image
imageroot/actions/clone-module/60systemd

During the move to another node we have an issue 
```
Jun 15 14:59:42 R2-pve.rocky9-pve2.org webserver6[2102]: task/module/webserver6/3febebd3-cab3-430a-b64b-945937d0bac9: clone-module/06copyenv is starting
Jun 15 14:59:43 R2-pve.rocky9-pve2.org webserver6[2102]: Traceback (most recent call last):
Jun 15 14:59:43 R2-pve.rocky9-pve2.org webserver6[2102]:   File "/home/webserver6/.config/actions/clone-module/06copyenv", line 29, in <module>
Jun 15 14:59:43 R2-pve.rocky9-pve2.org webserver6[2102]:     original_environment = request['environment']
Jun 15 14:59:43 R2-pve.rocky9-pve2.org webserver6[2102]: KeyError: 'environment'
Jun 15 14:59:43 R2-pve.rocky9-pve2.org webserver6[2102]: task/module/webserver6/3febebd3-cab3-430a-b64b-945937d0bac9: action "clone-module" status is "aborted" (1) at …
```

webserver move to another node is broken

---

build-images.sh

We have EOL coming for nginx (april 2024) and new version of SFTPGo 2.5.5
https://nginx.org/en/CHANGES
https://github.com/drakkan/sftpgo/releases

Upgrade SFTPGo 2.5.5  and Nginx 1.25.3

---

ui/public/i18n/en/translation.json
ui/src/views/Settings.vue

This pull request updates the SFTP TCP Port placeholder and type in the Settings view. The placeholder has been changed to "e.g. 3092" and the input type has been set to "number". This makes it clearer for users to enter the desired port number. Additionally, the translation for the tooltip has been updated to include the actual port number entered by the user. This improves the user experience and provides better guidance when configuring the SFTP TCP Port.
https://github.com/NethServer/dev/issues/6788

Update SFTP TCP Port placeholder and type

---

README.md

This pull request fixes custom nginx and php-fpm configurations in documentation . These changes allow for more flexibility and customization in the webserver setup.

Fix custom nginx and php-fpm configurations in documentation

---

imageroot/actions/create-vhost/validate-input.json
imageroot/actions/update-vhost/validate-input.json
ui/public/i18n/en/translation.json

This pull request fixes the validation pattern for the ServerNames field in the create-vhost and update-vhost actions. The pattern now requires a valid fully qualified domain name and disallows domain names with a dot at the end.
https://github.com/NethServer/dev/issues/6853

Fix validation pattern for ServerNames in create-vhost and update-vhost

---

README.md
imageroot/actions/create-vhost/validate-input.json
imageroot/actions/get-configuration/validate-output.json
imageroot/actions/update-vhost/validate-input.json
imageroot/bin/download-php-fpm
ui/public/i18n/en/translation.json
ui/src/views/VirtualHosts.vue

This pull request updates the PHP versions in the create-vhost and update-vhost commands to include PHP 8.3. It also updates the PhpVersion descriptions in the validate-input.json and validate-output.json files. Additionally, it adds PHP 8.3 to the translation.json file and includes it as an option in the VirtualHosts dropdown in the VirtualHosts.vue file.

Update PHP versions to include PHP 8.3

---

imageroot/actions/create-vhost/10base
imageroot/actions/destroy-vhost/validate-input.json
imageroot/actions/update-vhost/validate-input.json
tests/webserver.robot

When you create a virtualhost the folder is not created and when you try to reach the URL nginx gives back a 404 until you go to sftpgo to upload some files in the folder (here 9001). 
this is a bug because a 404 is unexpected, a 403 could be better understood
with my my PR nginx gives a 403 until you allow the root files indexing to allow to browse the files
This PR is also needed to finish the full test of the module, now we can after the virtualhost creation to test the vhost is reachable after the creation-vhost and the update-vhost action
the two fixes below are in the json schema of create-vhost and update vhost
This pull request adds a new "port" configuration option to the validate-input.json file in the imageroot/actions/update-vhost directory. The "port" option allows specifying …

Webserver : create the web folder with create folder

---

imageroot/actions/configure-module/20traefik
imageroot/actions/create-module/10configure
imageroot/actions/restore-module/06copyenv

An error occurred during the restoration because an environment variable related to the SFTPGo configuration was improperly handled, causing it to be out of range. This issue disrupted the restoration, leading to incorrect settings, such as the external SFTPGo access toggle being disabled despite being enabled before the backup. Proper handling of environment variables is essential to ensure all settings are restored accurately.
https://github.com/NethServer/dev/issues/6995

Restoration Error Due to Misconfigured Environment Variables

---

README.md

This pull request adds instructions for pulling website content directly from the container, providing an alternative method for content management. The instructions include connecting to the container, navigating to the root directory of the virtualhost, and using commands like wget, rsync, or git to retrieve the latest content. Permissions for the website can also be managed.

Add pull instructions for website content management

---

build-images.sh
imageroot/bin/download-php-fpm

This pull request updates the PHP and nginx versions in the project. The PHP version mappings have been updated to include the latest versions (8.1.30, 8.2.25, and 8.3.13). Similarly, the nginx version has been updated to 1.26.2-alpine and sftpgo to v2.6.2. 
https://github.com/NethServer/dev/issues/7083
why to upgrade
nginx is eol, lets go to stable
sftpgo gets a new UI, we do not have the limit anymore of 30 files
php get new updates

Update PHP, sftpgo and nginx versions

---

imageroot/actions/destroy-vhost/30restart_services
imageroot/actions/update-vhost/30SystemdServices

Correct the reload command for PHP-FPM in both destroy and update vhost actions to ensure proper service management.
https://github.com/NethServer/dev/issues/7194

Fix PHP-FPM reload command in vhost actions

---

imageroot/actions/create-vhost/30SystemdServices
imageroot/actions/update-vhost/30SystemdServices
imageroot/update-module.d/10fix_NextFpmPort

Ensure PHP-FPM services reload when configurations change or PHP versions are updated. Introduce a script to dynamically set the NextFpmPort based on existing virtual host IDs.
https://github.com/NethServer/dev/issues/7200

Reload PHP-FPM services after configuration changes and update NextFpmPort script

---

imageroot/bin/download-php-fpm

Update the version mappings for PHP-FPM to reflect the latest available releases.
https://github.com/NethServer/dev/issues/7234

Update PHP-FPM version mappings to latest releases

---

README.md
imageroot/etc/state-include.conf
imageroot/systemd/user/sftpgo.service

Include crontabs in the backup configuration, update the sftpgo service to create a crontabs directory and start the cron daemon, and add documentation for using cron within the sftpgo container. Additionally, enable rsync SSH commands in the sftpgo service configuration.

Add cron support to sftpgo container and update backup configuration

---

imageroot/actions/create-vhost/10base

The user of sftpgo is not used, some webapps like joomla complains about a lack of permission
see https://community.nethserver.org/t/rsync-to-virtual-host/25226
doing a chmod is needed to fix it 
/var/lib/sftpgo # chown bin:9002 /srv/sftpgo/data/9002/

fix(sftpgo): set owner of root folder to sftpgo user

---

imageroot/systemd/user/sftpgo.service

Enable the SCP command in the SFTP server configuration to enhance functionality.
https://community.nethserver.org/t/rsync-to-virtual-host/25226/37

Enable SCP command in SFTP server configuration

---

README.md
imageroot/actions/create-vhost/validate-input.json
imageroot/actions/get-configuration/validate-output.json
imageroot/actions/update-vhost/validate-input.json
imageroot/bin/download-php-fpm
ui/public/i18n/en/translation.json
ui/src/views/VirtualHosts.vue

Update the README and various schema files to include PHP 8.4 as an available version, ensuring consistency in dropdowns and validation descriptions.

Add PHP 8.4 support across documentation and configuration

---

build-images.sh
imageroot/bin/download-php-fpm

This pull request updates the base image version used for `nginx` and php 8.4 in the build process to ensure the latest features and security patches are included.
Dependency update:
* Updated the `org.nethserver.images` label in `build-images.sh` to reference `docker.io/nginx:1.28.0-alpine` instead of `1.27.5-alpine`
* upgrade php-fpm to 8.4.11
https://github.com/NethServer/dev/issues/7589

Updates the version used for nginx and php 8.4

---

build-images.sh
container/Containerfile
container/docker-php-ext-opcache.ini
imageroot/actions/clone-module/60pull-php-image
imageroot/actions/destroy-vhost/30restart_services
imageroot/actions/restore-module/60systemd
imageroot/actions/update-vhost/30SystemdServices
imageroot/bin/download-php-fpm
imageroot/bin/expand-vhosts
imageroot/systemd/user/phpfpm@.service
imageroot/templates/docker.conf
imageroot/templates/php-fpm-pool.conf
imageroot/templates/vhost-nginx.conf
imageroot/update-module.d/15clean-php-images
imageroot/update-module.d/20restart

This pull request introduces major improvements to the PHP-FPM container images and their integration into the system. It adds automated builds for multiple PHP versions, switches to official PHP images, updates configuration templates for better logging and compatibility, and refines service management logic to ensure only dynamic configurations are considered. Additionally, it provides a cleanup script to remove unused images and updates systemd and nginx integration for correct paths and improved reliability.
https://github.com/NethServer/dev/issues/7610
This version solves some issues we have with the previous version
- we build our version of php (from the php official), bitnami cannot offer us the free version with a tag like before. I have enabled the same php module that I could …

php-fpm: change upstream image to php project

---

build-images.sh
container/Containerfile

This pull request updates the PHP FPM container build process to use more specific and recent PHP base images, and refactors the Dockerfile to better support both Debian Bullseye and Trixie distributions.
During the verification @mrmarkuz pointed some php libraries were missing.
https://github.com/NethServer/dev/issues/7610

Update PHP version handling and dependencies for compatibility with Bullseye and Trixie

---

imageroot/state/customs/nginx.conf
imageroot/systemd/user/nginx.service

Introduce a custom Nginx configuration file that includes the X-Forwarded-For directive and update the systemd service to use this configuration.
https://github.com/NethServer/dev/issues/7640
even on a local network we see the IP of the server coming to the nginx logs, the traefik log is correc
without the fix (`192.168.12.110` is the external IP of the server, `192.168.13.25` is my client)
```
Sep 22 10:11:46 R1-pve.rocky9-pve.org nginx[3018330]: 192.168.12.110 - - [22/Sep/2025:08:11:46 +0000] "GET /phpinfo.php HTTP/1.1" 200 99208 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36" "192.168.13.25"
Sep 22 10:11:46 R1-pve.rocky9-pve.org traefik[3547]: 192.168.13.25 - - [22/Sep/2025:08:11:46 +0000] "GET /phpinfo.php HTTP/2.0" 200 99115 …
```

Add custom Nginx configuration with X-Forwarded-For support
